routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::group(['prefix'=>'admin'], function ()
{
    Route::resource('users','UsersController');
    Route::get('users/{id}/destroy',[
        'uses'=>'UsersController@destroy',
        'as'=>'users.destroy'
    ]);
    Route::resource('categories','CategoriesController')->middleware('auth');
    Route::get('categories/{id}/destroy',[
        'uses'=>'CategoriesController@destroy',
        'as'=>'categories.destroy'
    ])->middleware('auth');


    Route::resource('tags','TagsController')->middleware('auth');
    Route::get('tags/{id}/destroy',[
        'uses'=>'TagsController@destroy',
        'as'=>'tags.destroy'
    ])->middleware('auth');


    Route::resource('articles','ArticlesController')->middleware('auth');

});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('articles/{id}/destroy',[
    'uses'=>'ArticlesController@destroy',
    'as'=>'articles.destroy'
])->middleware('auth');


Route::get('breweries', ['middleware' => 'cors', function()
{
    return \Response::json(\App\Brewery::with('beers', 'geocode')->paginate(10), 200);
}]);

resources/views/admin/template/errors.blade.php
@if(count($errors)>0)

    <div class="alert alert-danger" role="alert">
        <ul>
            @foreach($errors->all() as $error)
                <li>
                    {{$error}}
                </li>
            @endforeach
        </ul>

    </div>

@endif

resources/views/admin/template/main.blade.php
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title','default')|Documento</title>
    <link rel="stylesheet" href="{{asset('plugins/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('plugins/chosen/chosen.css')}}">
    <link rel="stylesheet" href="{{asset('plugins/ui/trumbowyg.css')}}">

</head>
<body>
<div class="container">


        @include('admin.template.nav')

    <div class="row">
        <section>
            <div class="panel col-sm-offset-2 col-sm-8 col-sx-4 panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">@yield('title')</h3>
                </div>
                <div class="panel-body">

                    @include('flash::message')
                    @include('admin.template.errors')

                    @yield('content')

                </div>
            </div>

        </section>
    </div>




    <div class="footer">
        <div style="border-bottom: 1px solid #eee;margin-top: 30px;">

        </div>
        <div style="border-bottom: 1px solid #eee;margin-top: 10px;">
            <p>©2018</p>
        </div>

    </div>

</div>
<script src="{{asset('plugins/bootstrap/js/jquery.min.js')}}"></script>
<script src="{{asset('plugins/bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{asset('plugins/bootstrap/js/docs.min.js')}}"></script>
<script src="{{asset('plugins/chosen/chosen.jquery.js')}}"></script>
<script src="{{asset('plugins/trumbowyg.js')}}"></script>
@yield('js')
</body>
</html>

resources/views/admin/template/nav.blade.php
<div class="container">
<div style="border-radius: 6px" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
           
        </div>
        <div class="navbar-collapse collapse">
            <ul style="padding-left: 55px" class="nav navbar-nav">
                <li class="active"><a href="{{route('welcome')}}">Inicio</a></li>

                <li><a href="{{route('users.index')}}">Usuarios</a></li>
                <li><a href="{{route('categories.index')}}">Categorias</a></li>
                <li><a href="{{route('tags.index')}}">Tags</a></li>
                <li><a href="{{route('articles.index')}}">Articulos</a></li>
                
                
            </ul>

            <ul style="float:right;" class="nav navbar-nav">
                @guest
                <li ><a href="{{route('login')}}">Login</a></li>
                <li><a href="{{route('register')}}">Registrar</a></li>
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                    @endguest
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>
</div>
<div style="border-bottom: 1px solid #eee;margin-top: 60px;"></div>
<div style="margin-top: 10px" class="jumbotron">
  
    
</div>